import { v } from "convex/values";
const citedSignal = v.object({
  value: v.boolean(),
  source: v.string(),
  observedAt: v.number(),
});
export const companyFitInput = v.object({
  channels: v.array(
    v.object({
      country: v.string(),
      status: v.union(
        v.literal("NONE"),
        v.literal("DISTRIBUTOR_ONLY"),
        v.literal("EXCLUSIVE_AGENT"),
        v.literal("OWN_AFFILIATE"),
        v.literal("UNKNOWN"),
      ),
      partner: v.string(),
      productScope: v.string(),
      source: v.string(),
      observedAt: v.number(),
    }),
  ),
  staffCount: v.optional(v.number()),
  staffSource: v.string(),
  staffObservedAt: v.optional(v.number()),
  outLicensed: citedSignal,
  partneringContact: citedSignal,
  conferenceExhibitor: citedSignal,
});
export const forecastScenario = v.object({
  name: v.union(v.literal("downside"), v.literal("base"), v.literal("upside")),
  eligiblePatients: v.number(),
  reachablePct: v.number(),
  annualPatientGrowthPct: v.number(),
  adoptionPct: v.array(v.number()),
  unitsPerPatient: v.number(),
  netPrice: v.number(),
  annualPriceGrowthPct: v.number(),
  launchDelayMonths: v.number(),
  kemedicaSharePct: v.number(),
  unitCost: v.number(),
  annualOperatingCost: v.number(),
  upfrontCost: v.number(),
  workingCapitalPct: v.number(),
  probabilityOfSuccessPct: v.number(),
  publicSharePct: v.number(),
  tenderDiscountPct: v.number(),
  reimbursementReachPct: v.number(),
});
export const priceAnchor = v.object({
  kind: v.union(
    v.literal("germany_reference"),
    v.literal("gcc_registered"),
    v.literal("tender"),
    v.literal("directional"),
  ),
  country: v.string(),
  amount: v.number(),
  currency: v.string(),
  unitsPerPack: v.number(),
  unitBasis: v.string(),
  fxToUsd: v.number(),
  fxSource: v.string(),
  fxObservedAt: v.number(),
  priceType: v.string(),
  presentation: v.string(),
  source: v.string(),
  observedAt: v.number(),
  comparable: v.boolean(),
});
export const studyInput = v.object({
  therapeuticArea: v.string(),
  epidemiology: v.string(),
  targetPatients: v.string(),
  decisionMakers: v.string(),
  marketDynamics: v.string(),
  reimbursement: v.string(),
  affordability: v.string(),
  competition: v.string(),
  reputation: v.string(),
  willingness: v.string(),
  feasibility: v.string(),
  assumptionEvidence: v.string(),
  unitBasis: v.string(),
  startYear: v.number(),
  scenarios: v.array(forecastScenario),
  prices: v.array(priceAnchor),
});
export const accessEntry = v.object({
  name: v.string(),
  url: v.string(),
  finalUrl: v.optional(v.string()),
  status: v.union(
    v.literal("accessible"),
    v.literal("restricted"),
    v.literal("unavailable"),
    v.literal("directional"),
  ),
  httpStatus: v.optional(v.number()),
  note: v.string(),
  checkedAt: v.number(),
});
